# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
   include:
   - Infrastructure
  
pool:
  vmImage: 'ubuntu-latest'


# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

steps:

# Get secrets from the key vault
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)'
    KeyVaultName: 'widgetsprodbh5qtqj2ezp6m'
    SecretsFilter: 'pipeline'
    RunAsPreJob: false

- powershell: |
   $env:pipeline-infrastructure | Out-File ./parameters/parameters.prod.json
   workingDirectory: '/Infrastructure'

# Run the bicep deploy command
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)'
    ScriptType: 'InlineScript'
    Inline: 'az deployment group create --template-file ./main.bicep  --parameters ./parameters/parameters.prod.json -g "widgets-prod"'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
    workingDirectory: '/Infrastructure'
