# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
   include:
   - Infrastructure
  
pool:
  vmImage: 'windows-latest'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)'
    ScriptType: 'InlineScript'
    Inline: 'az deployment group create --template-file ./main.bicep  --parameters ./parameters/parameters.prod.json -g "widgets-prod"'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
    workingDirectory: '/Infrastructure'
