# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
   include:
   - UsermanagementInfrastructure
  



# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'


jobs:
- job: DeployInfrastructure
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  
  - task: PowerShell@2
    displayName: 'List Directory Contents'
    inputs:
      targetType: 'inline'
      script: 'ls'
      failOnStderr: true
      showWarnings: true
      workingDirectory: '$(Build.SourcesDirectory)/UsermanagementInfrastructure'  
