# https://medium.com/@karthi.net/kubernetes-tutorial-create-deployments-using-yaml-file-90ea901a2f74

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
  labels:
    app: UserManagementWebApi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserManagementWebApi
  template:
    metadata:
      labels:
        app: UserManagementWebApi
    spec:
      containers:
        - name: UserManagementWebApi
          image: UserManagementWebApi
          ports:
            - containerPort: 80