apiVersion: v1
kind: Service
metadata:
  name: user-management-web-api
  labels:
    app: user-management-web-api
spec:
  type: NodePort
  selector:
    app: user-management-web-api
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      nodePort: 30080 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
  
