# https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip#create-a-certificate-object
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: ingress-basic
spec:
  secretName: tls-secret
  dnsNames:
    - jellywidgets.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  # acme:
  #   config:
  #     - http01:
  #         ingressClass: nginx
  #       domains:
  #         - jellywidgets.com
  
