# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - UI

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

jobs:
  - job: DeployInfrastructure
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-latest"
    steps:

      # Get secrets from the key vault
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: "Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)"
          KeyVaultName: "widgetsprodbh5qtqj2ezp6m"
          SecretsFilter: "PipelineUI"
          RunAsPreJob: false

      # Prepare variables for consumption
      - task: PowerShell@2
        displayName: "Save variables to file"
        inputs:
          filePath: "UI/infrastructure/scripts/WriteParametersToFile.ps1"
          failOnStderr: true
          showWarnings: true
          workingDirectory: "$(Build.SourcesDirectory)/UI/infrastructure"
        env:
          PIPELINE_VARS: "$(PipelineUI)"

      # Run the deployment
      - task: AzurePowerShell@5
        displayName: "Deploy infrastructure using Bicep."
        inputs:
          azureSubscription: "Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)"
          ScriptType: FilePath
          ScriptPath: "UI/infrastructure/scripts/InvokeDeployment.ps1"
          FailOnStandardError: true
          azurePowerShellVersion: "LatestVersion"
          workingDirectory: "$(Build.SourcesDirectory)/UI/infrastructure"
