# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - UI

variables:
  system.debug: true
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

jobs:  

  - job: BuildUI
    timeoutInMinutes: 5
    pool:
      vmImage: "ubuntu-latest"
    steps:
    
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)/UI'
          customCommand: 'install'
          failOnStandardError: true
      - task: Npm@1
        displayName: 'Build the UI'
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)/UI'
          customCommand: 'run build'
          failOnStandardError: true  

      - task: AzureCLI@1
        displayName: Deploy the UI
        inputs:
          azureSubscription: $(azureSubscription)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch \
              --destination \$web \
              --account-name "$(storageAccountName)" \
              --source "$(Agent.BuildDirectory)/$(outputDir)"
              
  # This dependsOn can be removed if we end up with multiple agents. Slows down the builds without it.
  - job: DeployInfrastructure
    dependsOn: BuildUI
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-latest"
    steps:

      # Get secrets from the key vault
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: "Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)"
          KeyVaultName: "widgetsprodbh5qtqj2ezp6m"
          SecretsFilter: "PipelineUI"
          RunAsPreJob: false

      # Prepare variables for consumption
      - task: PowerShell@2
        displayName: "Save variables to file"
        inputs:
          filePath: "UI/infrastructure/scripts/WriteParametersToFile.ps1"
          failOnStderr: true
          showWarnings: true
          workingDirectory: "$(Build.SourcesDirectory)/UI/infrastructure"
        env:
          PIPELINE_VARS: "$(PipelineUI)"

      - task: AzureCLI@2
        displayName: 'Deploy infrastructure using Bicep.'
        inputs:
          azureSubscription: 'Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: 'az deployment group create --template-file ./main.bicep  --parameters "parameters/parameters.prod.json" -g "widgets-prod"'
          workingDirectory: '$(Build.SourcesDirectory)/UI/infrastructure'
          failOnStandardError: true