# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
   include:
   - Infrastructure
  



# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'


jobs:
- job: DeployInfrastructure
  timeoutInMinutes: 2
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  
  # Get secrets from the key vault
  - task: AzureKeyVault@1
    displayName: 'Get KeyVault Secrets'
    inputs:
      azureSubscription: 'Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)'
      KeyVaultName: 'widgetsprodbh5qtqj2ezp6m'
      SecretsFilter: 'PipelineInfrastructure'

   # - task: PowerShell@2
  #   displayName: 'List Directory Contents'
  #   inputs:
  #     targetType: 'inline'
  #     script: 'ls'
  #     failOnStderr: true
  #     showWarnings: true
  #     workingDirectory: '$(Build.SourcesDirectory)/Infrastructure' 

  # - task: PowerShell@2
  #   displayName: 'List Directory Contents'
  #   inputs:
  #     targetType: 'inline'
  #     script: 'ls scripts/*'
  #     failOnStderr: true
  #     showWarnings: true
  #     workingDirectory: '$(Build.SourcesDirectory)/Infrastructure'

  - task: Bash@3
    displayName: 'Display env vars'
    inputs:
      targetType: 'inline'
      script: 'env | sort'

  - task: PowerShell@2
    displayName: 'Save to file'
    inputs:
      filePath: 'Infrastructure/scripts/WriteParametersToFile.ps1'
      failOnStderr: true
      showWarnings: true
      workingDirectory: '$(Build.SourcesDirectory)/Infrastructure'
      arguments: $(PipelineInfrastructure)
      
  - task: AzurePowerShell@5
    displayName: 'Deploy infrastructure using Bicep.'
    inputs:
      azureSubscription: 'Chris Default Subscription(f21ccf56-7309-4e8a-9611-0f930fa6c2a4)'
      ScriptType: FilePath
      # Inline: 'az deployment group create --template-file ./main.bicep  --parameters "./parameters/parameters.prod.json" -g "widgets-prod"'
      ScriptPath: 'Infrastructure/scripts/InvokeDeployment.ps1'
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
      workingDirectory: '$(Build.SourcesDirectory)/Infrastructure'